server:
  port: 9296

spring:
  application:
    name: WYL-CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yashggoswami/wyl-config-server
          clone-on-start: true